spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/stayease_booking_db
    username: root
    password: 2000030757
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8085


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL


services:
  property:
    url: http://localhost:8084
  payment:
    url: http://localhost:8086
  notification:
    url: http://localhost:8087
  user:
    url: http://localhost:8082

resilience4j:
  retry:
    instances:
      userRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - feign.FeignException
          - java.io.IOException

  circuit breaker:
    instances:
      userCB:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
  feign:
    client:
      config:
        default:
          connectTimeout: 5000     # default ~1000ms
          readTimeout: 10000       # default ~2000ms

logging:
  level:
    root: INFO
    com.stayease.booking_service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
