spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/stayease_booking_db
    username: root
    password: 2000030757
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8085


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL


services:
  property:
    url: http://localhost:8084
  payment:
    url: http://localhost:8086
  notification:
    url: http://localhost:8087
  user:
    url: http://localhost:8082

resilience4j:
  circuit breaker:
    instances:
      paymentCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5000
        failureRateThreshold: 50
  retry:
    instances:
      paymentRetry:
        maxAttempts: 3
        waitDuration: 1000


logging:
  level:
    root: INFO
    com.stayease.booking_service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
